/* ==========================================
   kana-data.js — Complete Kana Data
   ========================================== */

const KANA = {
  /* ---- HIRAGANA BASIC (Gojūon) ---- */
  hiragana_basic: [
    // Row A
    { kana: 'あ', romaji: 'a' },
    { kana: 'い', romaji: 'i' },
    { kana: 'う', romaji: 'u' },
    { kana: 'え', romaji: 'e' },
    { kana: 'お', romaji: 'o' },
    // Row KA
    { kana: 'か', romaji: 'ka' },
    { kana: 'き', romaji: 'ki' },
    { kana: 'く', romaji: 'ku' },
    { kana: 'け', romaji: 'ke' },
    { kana: 'こ', romaji: 'ko' },
    // Row SA
    { kana: 'さ', romaji: 'sa' },
    { kana: 'し', romaji: 'shi' },
    { kana: 'す', romaji: 'su' },
    { kana: 'せ', romaji: 'se' },
    { kana: 'そ', romaji: 'so' },
    // Row TA
    { kana: 'た', romaji: 'ta' },
    { kana: 'ち', romaji: 'chi' },
    { kana: 'つ', romaji: 'tsu' },
    { kana: 'て', romaji: 'te' },
    { kana: 'と', romaji: 'to' },
    // Row NA
    { kana: 'な', romaji: 'na' },
    { kana: 'に', romaji: 'ni' },
    { kana: 'ぬ', romaji: 'nu' },
    { kana: 'ね', romaji: 'ne' },
    { kana: 'の', romaji: 'no' },
    // Row HA
    { kana: 'は', romaji: 'ha' },
    { kana: 'ひ', romaji: 'hi' },
    { kana: 'ふ', romaji: 'fu' },
    { kana: 'へ', romaji: 'he' },
    { kana: 'ほ', romaji: 'ho' },
    // Row MA
    { kana: 'ま', romaji: 'ma' },
    { kana: 'み', romaji: 'mi' },
    { kana: 'む', romaji: 'mu' },
    { kana: 'め', romaji: 'me' },
    { kana: 'も', romaji: 'mo' },
    // Row YA
    { kana: 'や', romaji: 'ya' },
    { kana: 'ゆ', romaji: 'yu' },
    { kana: 'よ', romaji: 'yo' },
    // Row RA
    { kana: 'ら', romaji: 'ra' },
    { kana: 'り', romaji: 'ri' },
    { kana: 'る', romaji: 'ru' },
    { kana: 'れ', romaji: 're' },
    { kana: 'ろ', romaji: 'ro' },
    // Row WA / N
    { kana: 'わ', romaji: 'wa' },
    { kana: 'を', romaji: 'wo' },
    { kana: 'ん', romaji: 'n' },
  ],

  /* ---- HIRAGANA DAKUON ---- */
  hiragana_dakuon: [
    // GA row
    { kana: 'が', romaji: 'ga' },
    { kana: 'ぎ', romaji: 'gi' },
    { kana: 'ぐ', romaji: 'gu' },
    { kana: 'げ', romaji: 'ge' },
    { kana: 'ご', romaji: 'go' },
    // ZA row
    { kana: 'ざ', romaji: 'za' },
    { kana: 'じ', romaji: 'ji' },
    { kana: 'ず', romaji: 'zu' },
    { kana: 'ぜ', romaji: 'ze' },
    { kana: 'ぞ', romaji: 'zo' },
    // DA row
    { kana: 'だ', romaji: 'da' },
    { kana: 'ぢ', romaji: 'ji' },
    { kana: 'づ', romaji: 'zu' },
    { kana: 'で', romaji: 'de' },
    { kana: 'ど', romaji: 'do' },
    // BA row
    { kana: 'ば', romaji: 'ba' },
    { kana: 'び', romaji: 'bi' },
    { kana: 'ぶ', romaji: 'bu' },
    { kana: 'べ', romaji: 'be' },
    { kana: 'ぼ', romaji: 'bo' },
  ],

  /* ---- HIRAGANA HANDAKUTEN ---- */
  hiragana_handakuten: [
    { kana: 'ぱ', romaji: 'pa' },
    { kana: 'ぴ', romaji: 'pi' },
    { kana: 'ぷ', romaji: 'pu' },
    { kana: 'ぺ', romaji: 'pe' },
    { kana: 'ぽ', romaji: 'po' },
  ],

  /* ---- HIRAGANA COMBINATION ---- */
  hiragana_combo: [
    { kana: 'きゃ', romaji: 'kya' },
    { kana: 'きゅ', romaji: 'kyu' },
    { kana: 'きょ', romaji: 'kyo' },
    { kana: 'しゃ', romaji: 'sha' },
    { kana: 'しゅ', romaji: 'shu' },
    { kana: 'しょ', romaji: 'sho' },
    { kana: 'ちゃ', romaji: 'cha' },
    { kana: 'ちゅ', romaji: 'chu' },
    { kana: 'ちょ', romaji: 'cho' },
    { kana: 'にゃ', romaji: 'nya' },
    { kana: 'にゅ', romaji: 'nyu' },
    { kana: 'にょ', romaji: 'nyo' },
    { kana: 'ひゃ', romaji: 'hya' },
    { kana: 'ひゅ', romaji: 'hyu' },
    { kana: 'ひょ', romaji: 'hyo' },
    { kana: 'みゃ', romaji: 'mya' },
    { kana: 'みゅ', romaji: 'myu' },
    { kana: 'みょ', romaji: 'myo' },
    { kana: 'りゃ', romaji: 'rya' },
    { kana: 'りゅ', romaji: 'ryu' },
    { kana: 'りょ', romaji: 'ryo' },
    { kana: 'ぎゃ', romaji: 'gya' },
    { kana: 'ぎゅ', romaji: 'gyu' },
    { kana: 'ぎょ', romaji: 'gyo' },
    { kana: 'じゃ', romaji: 'ja' },
    { kana: 'じゅ', romaji: 'ju' },
    { kana: 'じょ', romaji: 'jo' },
    { kana: 'びゃ', romaji: 'bya' },
    { kana: 'びゅ', romaji: 'byu' },
    { kana: 'びょ', romaji: 'byo' },
    { kana: 'ぴゃ', romaji: 'pya' },
    { kana: 'ぴゅ', romaji: 'pyu' },
    { kana: 'ぴょ', romaji: 'pyo' },
  ],

  /* ---- KATAKANA BASIC ---- */
  katakana_basic: [
    // Row A
    { kana: 'ア', romaji: 'a' },
    { kana: 'イ', romaji: 'i' },
    { kana: 'ウ', romaji: 'u' },
    { kana: 'エ', romaji: 'e' },
    { kana: 'オ', romaji: 'o' },
    // Row KA
    { kana: 'カ', romaji: 'ka' },
    { kana: 'キ', romaji: 'ki' },
    { kana: 'ク', romaji: 'ku' },
    { kana: 'ケ', romaji: 'ke' },
    { kana: 'コ', romaji: 'ko' },
    // Row SA
    { kana: 'サ', romaji: 'sa' },
    { kana: 'シ', romaji: 'shi' },
    { kana: 'ス', romaji: 'su' },
    { kana: 'セ', romaji: 'se' },
    { kana: 'ソ', romaji: 'so' },
    // Row TA
    { kana: 'タ', romaji: 'ta' },
    { kana: 'チ', romaji: 'chi' },
    { kana: 'ツ', romaji: 'tsu' },
    { kana: 'テ', romaji: 'te' },
    { kana: 'ト', romaji: 'to' },
    // Row NA
    { kana: 'ナ', romaji: 'na' },
    { kana: 'ニ', romaji: 'ni' },
    { kana: 'ヌ', romaji: 'nu' },
    { kana: 'ネ', romaji: 'ne' },
    { kana: 'ノ', romaji: 'no' },
    // Row HA
    { kana: 'ハ', romaji: 'ha' },
    { kana: 'ヒ', romaji: 'hi' },
    { kana: 'フ', romaji: 'fu' },
    { kana: 'ヘ', romaji: 'he' },
    { kana: 'ホ', romaji: 'ho' },
    // Row MA
    { kana: 'マ', romaji: 'ma' },
    { kana: 'ミ', romaji: 'mi' },
    { kana: 'ム', romaji: 'mu' },
    { kana: 'メ', romaji: 'me' },
    { kana: 'モ', romaji: 'mo' },
    // Row YA
    { kana: 'ヤ', romaji: 'ya' },
    { kana: 'ユ', romaji: 'yu' },
    { kana: 'ヨ', romaji: 'yo' },
    // Row RA
    { kana: 'ラ', romaji: 'ra' },
    { kana: 'リ', romaji: 'ri' },
    { kana: 'ル', romaji: 'ru' },
    { kana: 'レ', romaji: 're' },
    { kana: 'ロ', romaji: 'ro' },
    // Row WA / N
    { kana: 'ワ', romaji: 'wa' },
    { kana: 'ヲ', romaji: 'wo' },
    { kana: 'ン', romaji: 'n' },
  ],

  /* ---- KATAKANA DAKUON ---- */
  katakana_dakuon: [
    { kana: 'ガ', romaji: 'ga' },
    { kana: 'ギ', romaji: 'gi' },
    { kana: 'グ', romaji: 'gu' },
    { kana: 'ゲ', romaji: 'ge' },
    { kana: 'ゴ', romaji: 'go' },
    { kana: 'ザ', romaji: 'za' },
    { kana: 'ジ', romaji: 'ji' },
    { kana: 'ズ', romaji: 'zu' },
    { kana: 'ゼ', romaji: 'ze' },
    { kana: 'ゾ', romaji: 'zo' },
    { kana: 'ダ', romaji: 'da' },
    { kana: 'ヂ', romaji: 'ji' },
    { kana: 'ヅ', romaji: 'zu' },
    { kana: 'デ', romaji: 'de' },
    { kana: 'ド', romaji: 'do' },
    { kana: 'バ', romaji: 'ba' },
    { kana: 'ビ', romaji: 'bi' },
    { kana: 'ブ', romaji: 'bu' },
    { kana: 'ベ', romaji: 'be' },
    { kana: 'ボ', romaji: 'bo' },
  ],

  /* ---- KATAKANA HANDAKUTEN ---- */
  katakana_handakuten: [
    { kana: 'パ', romaji: 'pa' },
    { kana: 'ピ', romaji: 'pi' },
    { kana: 'プ', romaji: 'pu' },
    { kana: 'ペ', romaji: 'pe' },
    { kana: 'ポ', romaji: 'po' },
  ],

  /* ---- KATAKANA COMBINATION ---- */
  katakana_combo: [
    { kana: 'キャ', romaji: 'kya' },
    { kana: 'キュ', romaji: 'kyu' },
    { kana: 'キョ', romaji: 'kyo' },
    { kana: 'シャ', romaji: 'sha' },
    { kana: 'シュ', romaji: 'shu' },
    { kana: 'ショ', romaji: 'sho' },
    { kana: 'チャ', romaji: 'cha' },
    { kana: 'チュ', romaji: 'chu' },
    { kana: 'チョ', romaji: 'cho' },
    { kana: 'ニャ', romaji: 'nya' },
    { kana: 'ニュ', romaji: 'nyu' },
    { kana: 'ニョ', romaji: 'nyo' },
    { kana: 'ヒャ', romaji: 'hya' },
    { kana: 'ヒュ', romaji: 'hyu' },
    { kana: 'ヒョ', romaji: 'hyo' },
    { kana: 'ミャ', romaji: 'mya' },
    { kana: 'ミュ', romaji: 'myu' },
    { kana: 'ミョ', romaji: 'myo' },
    { kana: 'リャ', romaji: 'rya' },
    { kana: 'リュ', romaji: 'ryu' },
    { kana: 'リョ', romaji: 'ryo' },
    { kana: 'ギャ', romaji: 'gya' },
    { kana: 'ギュ', romaji: 'gyu' },
    { kana: 'ギョ', romaji: 'gyo' },
    { kana: 'ジャ', romaji: 'ja' },
    { kana: 'ジュ', romaji: 'ju' },
    { kana: 'ジョ', romaji: 'jo' },
    { kana: 'ビャ', romaji: 'bya' },
    { kana: 'ビュ', romaji: 'byu' },
    { kana: 'ビョ', romaji: 'byo' },
    { kana: 'ピャ', romaji: 'pya' },
    { kana: 'ピュ', romaji: 'pyu' },
    { kana: 'ピョ', romaji: 'pyo' },
  ],

  /* ---- HALF-WIDTH KATAKANA ---- */
  halfwidth_katakana: [
    { kana: 'ｱ', romaji: 'a' },
    { kana: 'ｲ', romaji: 'i' },
    { kana: 'ｳ', romaji: 'u' },
    { kana: 'ｴ', romaji: 'e' },
    { kana: 'ｵ', romaji: 'o' },
    { kana: 'ｶ', romaji: 'ka' },
    { kana: 'ｷ', romaji: 'ki' },
    { kana: 'ｸ', romaji: 'ku' },
    { kana: 'ｹ', romaji: 'ke' },
    { kana: 'ｺ', romaji: 'ko' },
    { kana: 'ｻ', romaji: 'sa' },
    { kana: 'ｼ', romaji: 'shi' },
    { kana: 'ｽ', romaji: 'su' },
    { kana: 'ｾ', romaji: 'se' },
    { kana: 'ｿ', romaji: 'so' },
    { kana: 'ﾀ', romaji: 'ta' },
    { kana: 'ﾁ', romaji: 'chi' },
    { kana: 'ﾂ', romaji: 'tsu' },
    { kana: 'ﾃ', romaji: 'te' },
    { kana: 'ﾄ', romaji: 'to' },
    { kana: 'ﾅ', romaji: 'na' },
    { kana: 'ﾆ', romaji: 'ni' },
    { kana: 'ﾇ', romaji: 'nu' },
    { kana: 'ﾈ', romaji: 'ne' },
    { kana: 'ﾉ', romaji: 'no' },
    { kana: 'ﾊ', romaji: 'ha' },
    { kana: 'ﾋ', romaji: 'hi' },
    { kana: 'ﾌ', romaji: 'fu' },
    { kana: 'ﾍ', romaji: 'he' },
    { kana: 'ﾎ', romaji: 'ho' },
    { kana: 'ﾏ', romaji: 'ma' },
    { kana: 'ﾐ', romaji: 'mi' },
    { kana: 'ﾑ', romaji: 'mu' },
    { kana: 'ﾒ', romaji: 'me' },
    { kana: 'ﾓ', romaji: 'mo' },
    { kana: 'ﾔ', romaji: 'ya' },
    { kana: 'ﾕ', romaji: 'yu' },
    { kana: 'ﾖ', romaji: 'yo' },
    { kana: 'ﾗ', romaji: 'ra' },
    { kana: 'ﾘ', romaji: 'ri' },
    { kana: 'ﾙ', romaji: 'ru' },
    { kana: 'ﾚ', romaji: 're' },
    { kana: 'ﾛ', romaji: 'ro' },
    { kana: 'ﾜ', romaji: 'wa' },
    { kana: 'ｦ', romaji: 'wo' },
    { kana: 'ﾝ', romaji: 'n' },
  ],
};

/* =========================================
   Table display definitions for Study section
   ========================================= */
const STUDY_TABLES = {
  hiragana: [
    {
      id: 'h-basic',
      title: 'Hiragana — Basic (平仮名 基本)',
      badge: 'Gojūon',
      badgeColor: 'bg-pink-100 text-pink-700 dark:bg-pink-900/30 dark:text-pink-300',
      data: KANA.hiragana_basic,
      rows: [
        [{kana:'あ',romaji:'a'}, {kana:'い',romaji:'i'}, {kana:'う',romaji:'u'}, {kana:'え',romaji:'e'}, {kana:'お',romaji:'o'}],
        [{kana:'か',romaji:'ka'},{kana:'き',romaji:'ki'},{kana:'く',romaji:'ku'},{kana:'け',romaji:'ke'},{kana:'こ',romaji:'ko'}],
        [{kana:'さ',romaji:'sa'},{kana:'し',romaji:'shi'},{kana:'す',romaji:'su'},{kana:'せ',romaji:'se'},{kana:'そ',romaji:'so'}],
        [{kana:'た',romaji:'ta'},{kana:'ち',romaji:'chi'},{kana:'つ',romaji:'tsu'},{kana:'て',romaji:'te'},{kana:'と',romaji:'to'}],
        [{kana:'な',romaji:'na'},{kana:'に',romaji:'ni'},{kana:'ぬ',romaji:'nu'},{kana:'ね',romaji:'ne'},{kana:'の',romaji:'no'}],
        [{kana:'は',romaji:'ha'},{kana:'ひ',romaji:'hi'},{kana:'ふ',romaji:'fu'},{kana:'へ',romaji:'he'},{kana:'ほ',romaji:'ho'}],
        [{kana:'ま',romaji:'ma'},{kana:'み',romaji:'mi'},{kana:'む',romaji:'mu'},{kana:'め',romaji:'me'},{kana:'も',romaji:'mo'}],
        [{kana:'や',romaji:'ya'}, null,               {kana:'ゆ',romaji:'yu'}, null,               {kana:'よ',romaji:'yo'}],
        [{kana:'ら',romaji:'ra'},{kana:'り',romaji:'ri'},{kana:'る',romaji:'ru'},{kana:'れ',romaji:'re'},{kana:'ろ',romaji:'ro'}],
        [{kana:'わ',romaji:'wa'}, null,               null,                   null,               {kana:'を',romaji:'wo'}],
        [{kana:'ん',romaji:'n'},  null,               null,                   null,               null                   ],
      ],
    },
    {
      id: 'h-dakuon',
      title: 'Hiragana — Dakuon (濁音)',
      badge: '゛',
      badgeColor: 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300',
      data: KANA.hiragana_dakuon,
      rows: [
        [{kana:'が',romaji:'ga'},{kana:'ぎ',romaji:'gi'},{kana:'ぐ',romaji:'gu'},{kana:'げ',romaji:'ge'},{kana:'ご',romaji:'go'}],
        [{kana:'ざ',romaji:'za'},{kana:'じ',romaji:'ji'},{kana:'ず',romaji:'zu'},{kana:'ぜ',romaji:'ze'},{kana:'ぞ',romaji:'zo'}],
        [{kana:'だ',romaji:'da'},{kana:'ぢ',romaji:'ji'},{kana:'ず',romaji:'zu'},{kana:'で',romaji:'de'},{kana:'ど',romaji:'do'}],
        [{kana:'ば',romaji:'ba'},{kana:'び',romaji:'bi'},{kana:'ぶ',romaji:'bu'},{kana:'べ',romaji:'be'},{kana:'ぼ',romaji:'bo'}],
      ],
    },
    {
      id: 'h-handakuten',
      title: 'Hiragana — Handakuten (半濁音)',
      badge: '゜',
      badgeColor: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300',
      data: KANA.hiragana_handakuten,
      rows: [
        [{kana:'ぱ',romaji:'pa'},{kana:'ぴ',romaji:'pi'},{kana:'ぷ',romaji:'pu'},{kana:'ぺ',romaji:'pe'},{kana:'ぽ',romaji:'po'}],
      ],
    },
    {
      id: 'h-combo',
      title: 'Hiragana — Combinations (組み合わせ)',
      badge: 'Combo',
      badgeColor: 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300',
      data: KANA.hiragana_combo,
      rows: [
        [{kana:'きゃ',romaji:'kya'},{kana:'きゅ',romaji:'kyu'},{kana:'きょ',romaji:'kyo'}],
        [{kana:'しゃ',romaji:'sha'},{kana:'しゅ',romaji:'shu'},{kana:'しょ',romaji:'sho'}],
        [{kana:'ちゃ',romaji:'cha'},{kana:'ちゅ',romaji:'chu'},{kana:'ちょ',romaji:'cho'}],
        [{kana:'にゃ',romaji:'nya'},{kana:'にゅ',romaji:'nyu'},{kana:'にょ',romaji:'nyo'}],
        [{kana:'ひゃ',romaji:'hya'},{kana:'ひゅ',romaji:'hyu'},{kana:'ひょ',romaji:'hyo'}],
        [{kana:'みゃ',romaji:'mya'},{kana:'みゅ',romaji:'myu'},{kana:'みょ',romaji:'myo'}],
        [{kana:'りゃ',romaji:'rya'},{kana:'りゅ',romaji:'ryu'},{kana:'りょ',romaji:'ryo'}],
        [{kana:'ぎゃ',romaji:'gya'},{kana:'ぎゅ',romaji:'gyu'},{kana:'ぎょ',romaji:'gyo'}],
        [{kana:'じゃ',romaji:'ja'}, {kana:'じゅ',romaji:'ju'}, {kana:'じょ',romaji:'jo'} ],
        [{kana:'びゃ',romaji:'bya'},{kana:'びゅ',romaji:'byu'},{kana:'びょ',romaji:'byo'}],
        [{kana:'ぴゃ',romaji:'pya'},{kana:'ぴゅ',romaji:'pyu'},{kana:'ぴょ',romaji:'pyo'}],
      ],
    },
  ],
  katakana: [
    {
      id: 'k-basic',
      title: 'Katakana — Basic (片仮名 基本)',
      badge: 'Gojūon',
      badgeColor: 'bg-pink-100 text-pink-700 dark:bg-pink-900/30 dark:text-pink-300',
      data: KANA.katakana_basic,
      rows: [
        [{kana:'ア',romaji:'a'}, {kana:'イ',romaji:'i'}, {kana:'ウ',romaji:'u'}, {kana:'エ',romaji:'e'}, {kana:'オ',romaji:'o'}],
        [{kana:'カ',romaji:'ka'},{kana:'キ',romaji:'ki'},{kana:'ク',romaji:'ku'},{kana:'ケ',romaji:'ke'},{kana:'コ',romaji:'ko'}],
        [{kana:'サ',romaji:'sa'},{kana:'シ',romaji:'shi'},{kana:'ス',romaji:'su'},{kana:'セ',romaji:'se'},{kana:'ソ',romaji:'so'}],
        [{kana:'タ',romaji:'ta'},{kana:'チ',romaji:'chi'},{kana:'ツ',romaji:'tsu'},{kana:'テ',romaji:'te'},{kana:'ト',romaji:'to'}],
        [{kana:'ナ',romaji:'na'},{kana:'ニ',romaji:'ni'},{kana:'ヌ',romaji:'nu'},{kana:'ネ',romaji:'ne'},{kana:'ノ',romaji:'no'}],
        [{kana:'ハ',romaji:'ha'},{kana:'ヒ',romaji:'hi'},{kana:'フ',romaji:'fu'},{kana:'ヘ',romaji:'he'},{kana:'ホ',romaji:'ho'}],
        [{kana:'マ',romaji:'ma'},{kana:'ミ',romaji:'mi'},{kana:'ム',romaji:'mu'},{kana:'メ',romaji:'me'},{kana:'モ',romaji:'mo'}],
        [{kana:'ヤ',romaji:'ya'}, null,               {kana:'ユ',romaji:'yu'}, null,               {kana:'ヨ',romaji:'yo'}],
        [{kana:'ラ',romaji:'ra'},{kana:'リ',romaji:'ri'},{kana:'ル',romaji:'ru'},{kana:'レ',romaji:'re'},{kana:'ロ',romaji:'ro'}],
        [{kana:'ワ',romaji:'wa'}, null,               null,                   null,               {kana:'ヲ',romaji:'wo'}],
        [{kana:'ン',romaji:'n'},  null,               null,                   null,               null                   ],
      ],
    },
    {
      id: 'k-dakuon',
      title: 'Katakana — Dakuon (濁音)',
      badge: '゛',
      badgeColor: 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300',
      data: KANA.katakana_dakuon,
      rows: [
        [{kana:'ガ',romaji:'ga'},{kana:'ギ',romaji:'gi'},{kana:'グ',romaji:'gu'},{kana:'ゲ',romaji:'ge'},{kana:'ゴ',romaji:'go'}],
        [{kana:'ザ',romaji:'za'},{kana:'ジ',romaji:'ji'},{kana:'ズ',romaji:'zu'},{kana:'ゼ',romaji:'ze'},{kana:'ゾ',romaji:'zo'}],
        [{kana:'ダ',romaji:'da'},{kana:'ヂ',romaji:'ji'},{kana:'ヅ',romaji:'zu'},{kana:'デ',romaji:'de'},{kana:'ド',romaji:'do'}],
        [{kana:'バ',romaji:'ba'},{kana:'ビ',romaji:'bi'},{kana:'ブ',romaji:'bu'},{kana:'ベ',romaji:'be'},{kana:'ボ',romaji:'bo'}],
      ],
    },
    {
      id: 'k-handakuten',
      title: 'Katakana — Handakuten (半濁音)',
      badge: '゜',
      badgeColor: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300',
      data: KANA.katakana_handakuten,
      rows: [
        [{kana:'パ',romaji:'pa'},{kana:'ピ',romaji:'pi'},{kana:'プ',romaji:'pu'},{kana:'ペ',romaji:'pe'},{kana:'ポ',romaji:'po'}],
      ],
    },
    {
      id: 'k-combo',
      title: 'Katakana — Combinations (組み合わせ)',
      badge: 'Combo',
      badgeColor: 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300',
      data: KANA.katakana_combo,
      rows: [
        [{kana:'キャ',romaji:'kya'},{kana:'キュ',romaji:'kyu'},{kana:'キョ',romaji:'kyo'}],
        [{kana:'シャ',romaji:'sha'},{kana:'シュ',romaji:'shu'},{kana:'ショ',romaji:'sho'}],
        [{kana:'チャ',romaji:'cha'},{kana:'チュ',romaji:'chu'},{kana:'チョ',romaji:'cho'}],
        [{kana:'ニャ',romaji:'nya'},{kana:'ニュ',romaji:'nyu'},{kana:'ニョ',romaji:'nyo'}],
        [{kana:'ヒャ',romaji:'hya'},{kana:'ヒュ',romaji:'hyu'},{kana:'ヒョ',romaji:'hyo'}],
        [{kana:'ミャ',romaji:'mya'},{kana:'ミュ',romaji:'myu'},{kana:'ミョ',romaji:'myo'}],
        [{kana:'リャ',romaji:'rya'},{kana:'リュ',romaji:'ryu'},{kana:'リョ',romaji:'ryo'}],
        [{kana:'ギャ',romaji:'gya'},{kana:'ギュ',romaji:'gyu'},{kana:'ギョ',romaji:'gyo'}],
        [{kana:'ジャ',romaji:'ja'}, {kana:'ジュ',romaji:'ju'}, {kana:'ジョ',romaji:'jo'} ],
        [{kana:'ビャ',romaji:'bya'},{kana:'ビュ',romaji:'byu'},{kana:'ビョ',romaji:'byo'}],
        [{kana:'ピャ',romaji:'pya'},{kana:'ピュ',romaji:'pyu'},{kana:'ピョ',romaji:'pyo'}],
      ],
    },
  ],
};
